crop_type_individual_encoding = {
    "Agricultural natural mixture": 1,
    "Barley, summer-": 2,
    "Barley, winter-": 3,
    "Beets, sugar-": 4,
    "Clover": 5,
    "Maize": 6,
    "Ethiopian mustard": 8,
    "Grassland, temporary": 7,
    "Japanese oats": 24,
    "Leaf radish": 10,
    "(Naked) Oats": 9,
    "Other green manures": 23,
    "Potatoes": 11,
    "Rapeseed, summer (incl. butterseed)": 12,
    "Rapeseed, winter (incl. butterseed)": 20,
    "Rye (not cut rye)": 13,
    "Soybeans": 14,
    "Sudan grass/Sorghum": 15,
    "Sunflowers": 16,
    "Tagetes erecta/patula - (African) Marigold": 17,
    "Triticale": 18,
    "Vetch, fodder/variegated": 19,
    "Wheat, summer": 21,
    "Wheat, winter-": 22,
    "Yellow/Black mustard": 25,
    "Phacelia": 0,
}

